version: "3"
services:
  db:
    image: postgres:13
    volumes:
      - ./seed:/var/lib/postgresql/seed
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"